### ISSUE TITLE
Error in production build with Maven plugin 24.4.0.alpha15

### ISSUE THREAD

**Issue by stefanbrenner** [vaadin/platform#5181]
### Describe the bug

With the Maven plugin (24.4.0.alpha15) I get the following error on building the application with production mode
`error TS2353: Object literal may only specify known properties, and 'continue' does not exist in type 'PreventCommands'.`

`
Execution default of goal com.vaadin:vaadin-maven-plugin:24.4.0.alpha15:build-frontend failed: Vite process exited with non-zero exit code.
[ERROR] Stderr: 'vite v5.1.6 building for production...
[ERROR] transforming...
[ERROR] frontend/generated/flow/Flow.tsx(187,17): error TS2353: Object literal may only specify known properties, and 'continue' does not exist in type 'PreventCommands'.
`

### Reproduction

```xml
<profiles>
    <profile>
        <id>production</id>
        <properties>
            <vaadin.productionMode>true</vaadin.productionMode>
        </properties>

        <build>
            <plugins>
                <plugin>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <goals>
                                <goal>build-frontend</goal>
                            </goals>
                            <phase>compile</phase>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </build>
    </profile>
</profiles>
```

mvn clean install -Pproduction

### System Info

OSX Sonoma 14.4 (23E214)
Vaadin 24.4.0.alpha15
